Repository np-guard/netpol-analyzer, pull requests merged in 2023-11, with the labels that each got.

#259 adding test flag to override/generate golden files
  Makefile
  pkg/netpol/internal/testutils/utils.go
Labels: size/S

#260 avoid ingress-controller name and ns duplication
  pkg/netpol/common/netpol_commands_common.go
  pkg/netpol/connlist/connlist.go
  pkg/netpol/connlist/internal/ingressanalyzer/ingress_analyzer.go
  pkg/netpol/diff/diff.go
Labels: size/S

#269 update make-relase
  .github/workflows/make-release.yaml
Labels: size/XS

#270 moving diffAnalyzer to a new file
  pkg/netpol/diff/diff.go
  pkg/netpol/diff/diff_analyzer.go
Labels: size/L

#271 Issue 265 moving pkgs
  cmd/netpolicy/cmd/diff.go
  cmd/netpolicy/cmd/evaluate.go
  cmd/netpolicy/cmd/list.go
  cmd/netpolicy/cmd/root.go
  pkg/logger/logger.go
  pkg/manifests/fsscanner/manifests.go
  pkg/manifests/fsscanner/manifests_test.go
  pkg/manifests/parser/error_types.go
  pkg/manifests/parser/k8sobj.go
  pkg/manifests/parser/parser.go
  pkg/netpol/connlist/connlist.go
  pkg/netpol/connlist/connlist_test.go
  pkg/netpol/connlist/internal/ingressanalyzer/ingress_analyzer.go
  pkg/netpol/connlist/internal/ingressanalyzer/ingress_analyzer_test.go
  pkg/netpol/connlist/internal/ingressanalyzer/service_test.go
  pkg/netpol/diff/diff.go
  pkg/netpol/diff/diff_analyzer.go
  pkg/netpol/diff/diff_test.go
  pkg/netpol/eval/eval_test.go
  pkg/netpol/eval/internal/k8s/pod.go
  pkg/netpol/eval/resources.go
Labels: size/M

#274 Issue 241 generate also png for dot output
  Makefile
  pkg/internal/testutils/testutils.go
  tests/acs-security-demos-added-workloads/diff_output_from_acs-security-demos.dot.svg
  tests/acs-security-demos-new/diff_output_from_acs-security-demos.dot.png
  tests/acs-security-demos-new/diff_output_from_acs-security-demos.dot.svg
  tests/acs-security-demos/connlist_output.dot.svg
  tests/acs_security_frontend_demos/connlist_output.dot.png
  tests/acs_security_frontend_demos/connlist_output.dot.svg
  tests/demo_app_with_routes_and_ingress/connlist_output.dot.svg
  tests/k8s_ingress_test/connlist_output.dot.svg
  tests/k8s_ingress_test_new/diff_output_from_k8s_ingress_test.dot.png
  tests/k8s_ingress_test_new/diff_output_from_k8s_ingress_test.dot.svg
  tests/multiple_ingress_objects_with_different_ports/connlist_output.dot.svg
  tests/multiple_ingress_objects_with_different_ports_new/diff_output_from_multiple_ingress_objects_with_different_ports.dot.png
  tests/multiple_ingress_objects_with_different_ports_new/diff_output_from_multiple_ingress_objects_with_different_ports.dot.svg
  tests/netpol-diff-example-minimal/diff_output_from_netpol-analysis-example-minimal.dot.png
  tests/netpol-diff-example-minimal/diff_output_from_netpol-analysis-example-minimal.dot.svg
  tests/one_ingress_multiple_ports/connlist_output.dot.svg
  tests/one_ingress_multiple_services/connlist_output.dot.svg
  tests/onlineboutique_workloads/connlist_output.dot.svg
  tests/onlineboutique_workloads_changed_netpols/TsetOutputWithArgNamesOption.dot.png
  tests/onlineboutique_workloads_changed_netpols/TsetOutputWithArgNamesOption.dot.svg
  tests/onlineboutique_workloads_changed_netpols/diff_output_from_onlineboutique_workloads.dot.png
  tests/onlineboutique_workloads_changed_netpols/diff_output_from_onlineboutique_workloads.dot.svg
  tests/onlineboutique_workloads_changed_netpols_and_workloads/diff_output_from_onlineboutique_workloads.dot.png
  tests/onlineboutique_workloads_changed_netpols_and_workloads/diff_output_from_onlineboutique_workloads.dot.svg
  tests/onlineboutique_workloads_changed_workloads/diff_output_from_onlineboutique_workloads.dot.svg
Labels: size/XXL
