Repository np-guard/netpol-analyzer, pull requests merged in 2024-02, with the labels that each got.

#305 Adding more linters and fixing the errors they find
  .golangci.yml
  pkg/cli/evaluate.go
  pkg/manifests/fsscanner/manifests.go
  pkg/manifests/parser/parser.go
Labels: size/M

#306 pre proccessing policy for general conns
  pkg/netpol/connlist/connlist.go
  pkg/netpol/connlist/internal/ingressanalyzer/ingress_analyzer.go
  pkg/netpol/eval/check.go
  pkg/netpol/eval/internal/k8s/client.go
  pkg/netpol/eval/internal/k8s/netpol.go
  pkg/netpol/eval/internal/k8s/pod.go
  pkg/netpol/eval/resources.go
  pkg/netpol/internal/common/CanonicalIntervalSet.go
  pkg/netpol/internal/common/connectionset.go
  pkg/netpol/internal/common/portset.go
Labels: size/L

#307 Policy engine with new api func for exposure analysis
  pkg/netpol/connlist/connlist.go
  pkg/netpol/eval/check.go
  pkg/netpol/eval/internal/k8s/netpol.go
  pkg/netpol/eval/internal/k8s/pod.go
  pkg/netpol/eval/resources.go
Labels: size/L

#309 adding representativePeer struct
  pkg/internal/netpolerrors/netpol_errors.go
  pkg/netpol/connlist/connlist.go
  pkg/netpol/connlist/exposure_map.go
  pkg/netpol/eval/check.go
  pkg/netpol/eval/exposure.go
  pkg/netpol/eval/internal/k8s/netpol.go
  pkg/netpol/eval/internal/k8s/peer.go
  pkg/netpol/eval/internal/k8s/pod.go
  pkg/netpol/eval/resources.go
  pkg/netpol/internal/common/exposure_resources_names.go
Labels: size/L

#315 Running golangci-lint action according to docs
  .github/workflows/golangci-lint.yml
  pkg/netpol/eval/internal/k8s/client.go
Labels: size/S
