Repository np-guard/netpol-analyzer, pull requests merged in 2024-05, with the labels that each got.

#342 support for golangci lint 1.58.0
  .golangci.yml
  pkg/netpol/connlist/internal/ingressanalyzer/ingress_analyzer.go
Labels: size/XS

#344 update .golangci.yml
  .golangci.yml
  cmd/netpolicy/main.go
  pkg/cli/command_test.go
  pkg/cli/diff.go
  pkg/cli/evaluate.go
  pkg/cli/list.go
  pkg/cli/root.go
  pkg/internal/netpolerrors/netpol_errors.go
  pkg/internal/output/output.go
  pkg/internal/projectpath/projectpath.go
  pkg/internal/testutils/testutils.go
  pkg/logger/logger.go
  pkg/manifests/fsscanner/manifests.go
  pkg/manifests/fsscanner/manifests_test.go
  pkg/manifests/parser/error_types.go
  pkg/manifests/parser/k8sobj.go
  pkg/manifests/parser/parser.go
  pkg/netpol/connlist/connlist.go
  pkg/netpol/connlist/connlist_errors.go
  pkg/netpol/connlist/connlist_test.go
  pkg/netpol/connlist/conns_formatter.go
  pkg/netpol/connlist/conns_formatter_csv.go
  pkg/netpol/connlist/conns_formatter_dot.go
  pkg/netpol/connlist/conns_formatter_json.go
  pkg/netpol/connlist/conns_formatter_md.go
  pkg/netpol/connlist/conns_formatter_txt.go
  pkg/netpol/connlist/internal/ingressanalyzer/ingress_analyzer.go
  pkg/netpol/connlist/internal/ingressanalyzer/ingress_analyzer_test.go
  pkg/netpol/connlist/internal/ingressanalyzer/service_test.go
  pkg/netpol/connlist/peer2peer.go
  pkg/netpol/diff/connectivity_diff.go
  pkg/netpol/diff/diff.go
  pkg/netpol/diff/diff_analyzer.go
  pkg/netpol/diff/diff_errors.go
  pkg/netpol/diff/diff_formatter.go
  pkg/netpol/diff/diff_formatter_csv.go
  pkg/netpol/diff/diff_formatter_dot.go
  pkg/netpol/diff/diff_formatter_md.go
  pkg/netpol/diff/diff_formatter_text.go
  pkg/netpol/diff/diff_test.go
  pkg/netpol/eval/check.go
  pkg/netpol/eval/eval_cache.go
  pkg/netpol/eval/eval_test.go
  pkg/netpol/eval/internal/k8s/client.go
  pkg/netpol/eval/internal/k8s/namespace.go
  pkg/netpol/eval/internal/k8s/netpol.go
  pkg/netpol/eval/internal/k8s/netpol_test.go
  pkg/netpol/eval/internal/k8s/peer.go
  pkg/netpol/eval/internal/k8s/pod.go
  pkg/netpol/eval/peer.go
  pkg/netpol/eval/resources.go
  pkg/netpol/internal/common/connection.go
  pkg/netpol/internal/common/connectionset.go
  pkg/netpol/internal/common/netpol_commands_common.go
  pkg/netpol/internal/common/portset.go
  pkg/netpol/internal/dotformatting/dot_output_formatting.go
Labels: size/XL

#350 Makefile update
  Makefile
Labels: size/XS

#352 don't remove representative peers in any-namespace
  pkg/netpol/connlist/connlist_test.go
  pkg/netpol/eval/exposure.go
  test_outputs/connlist/demo_app_with_routes_and_ingress_connlist_output.dot.svg
  test_outputs/connlist/exposure_test_conn_to_all_pods_in_an_existing_ns_connlist_output.dot
  test_outputs/connlist/exposure_test_conn_to_all_pods_in_an_existing_ns_connlist_output.dot.png
  test_outputs/connlist/exposure_test_conn_to_all_pods_in_an_existing_ns_connlist_output.dot.svg
  test_outputs/connlist/exposure_test_conn_to_all_pods_in_an_existing_ns_connlist_output.txt
  test_outputs/connlist/exposure_test_conn_to_all_pods_in_an_existing_ns_with_ns_selector_only_connlist_output.dot
  test_outputs/connlist/exposure_test_conn_to_all_pods_in_an_existing_ns_with_ns_selector_only_connlist_output.dot.png
  test_outputs/connlist/exposure_test_conn_to_all_pods_in_an_existing_ns_with_ns_selector_only_connlist_output.dot.svg
  test_outputs/connlist/exposure_test_conn_to_all_pods_in_an_existing_ns_with_ns_selector_only_connlist_output.txt
  test_outputs/connlist/exposure_test_conn_to_new_pod_in_an_existing_ns_connlist_output.dot
  test_outputs/connlist/exposure_test_conn_to_new_pod_in_an_existing_ns_connlist_output.dot.png
  test_outputs/connlist/exposure_test_conn_to_new_pod_in_an_existing_ns_connlist_output.dot.svg
  test_outputs/connlist/exposure_test_conn_to_new_pod_in_an_existing_ns_connlist_output.txt
  test_outputs/connlist/exposure_test_conn_with_pod_selector_in_any_ns_connlist_output.dot.svg
  test_outputs/connlist/exposure_test_exposure_to_any_namespace_with_podSelector_connlist_output.dot
  test_outputs/connlist/exposure_test_exposure_to_any_namespace_with_podSelector_connlist_output.dot.png
  test_outputs/connlist/exposure_test_exposure_to_any_namespace_with_podSelector_connlist_output.dot.svg
  test_outputs/connlist/exposure_test_exposure_to_any_namespace_with_podSelector_connlist_output.txt
  test_outputs/connlist/exposure_test_exposure_to_namespace_except_specific_pod_connlist_output.dot
  test_outputs/connlist/exposure_test_exposure_to_namespace_except_specific_pod_connlist_output.dot.png
  test_outputs/connlist/exposure_test_exposure_to_namespace_except_specific_pod_connlist_output.dot.svg
  test_outputs/connlist/exposure_test_exposure_to_namespace_except_specific_pod_connlist_output.txt
  tests/test_conn_to_all_pods_in_an_existing_ns/backend.yaml
  tests/test_conn_to_all_pods_in_an_existing_ns/netpol.yaml
  tests/test_conn_to_all_pods_in_an_existing_ns/ns_and_deployments.yaml
  tests/test_conn_to_all_pods_in_an_existing_ns_with_ns_selector_only/backend.yaml
  tests/test_conn_to_all_pods_in_an_existing_ns_with_ns_selector_only/netpol.yaml
  tests/test_conn_to_all_pods_in_an_existing_ns_with_ns_selector_only/ns_and_deployments.yaml
  tests/test_conn_to_new_pod_in_an_existing_ns/backend.yaml
  tests/test_conn_to_new_pod_in_an_existing_ns/netpol.yaml
  tests/test_conn_to_new_pod_in_an_existing_ns/ns_and_deployments.yaml
  tests/test_exposure_to_any_namespace_with_podSelector/backend.yaml
  tests/test_exposure_to_any_namespace_with_podSelector/frontend.yaml
  tests/test_exposure_to_any_namespace_with_podSelector/netpols.yaml
  tests/test_exposure_to_namespace_except_specific_pod/backend.yaml
  tests/test_exposure_to_namespace_except_specific_pod/backend_netpol.yaml
  tests/test_exposure_to_namespace_except_specific_pod/hello_world_netpol.yaml
  tests/test_exposure_to_namespace_except_specific_pod/ns_and_deployments.yaml
  tests/test_matched_and_unmatched_rules/netpol.yaml
  tests/test_new_namespace_conn_and_entire_cluster/netpol.yaml
  tests/test_only_matched_rules/netpol.yaml
Labels: size/XXL
