Repository np-guard/netpol-analyzer, pull requests merged in 2024-03, with the labels that each got.

#314 Optimize representative peers generation
  pkg/netpol/connlist/connlist.go
  pkg/netpol/eval/exposure.go
  pkg/netpol/eval/internal/k8s/namespace.go
  pkg/netpol/eval/internal/k8s/netpol.go
  pkg/netpol/eval/internal/k8s/peer.go
  pkg/netpol/eval/internal/k8s/pod.go
  pkg/netpol/eval/resources.go
Labels: size/L

#321 update go version 1.21
  .github/workflows/go-build.yml
  .github/workflows/make-release.yaml
  README.md
  go.mod
  go.sum
Labels: size/S

#323 Use models v0.2.1
  go.mod
  go.sum
  pkg/netpol/connlist/connlist.go
  pkg/netpol/connlist/internal/ingressanalyzer/ingress_analyzer.go
  pkg/netpol/eval/check.go
  pkg/netpol/eval/eval_test.go
  pkg/netpol/eval/internal/k8s/netpol.go
  pkg/netpol/eval/internal/k8s/peer.go
  pkg/netpol/eval/internal/k8s/pod.go
  pkg/netpol/eval/peer.go
  pkg/netpol/eval/resources.go
  pkg/netpol/internal/common/CanonicalIntervalSet.go
  pkg/netpol/internal/common/connectionset.go
  pkg/netpol/internal/common/intervals_test.go
  pkg/netpol/internal/common/ipBlock.go
  pkg/netpol/internal/common/ipBlock_test.go
  pkg/netpol/internal/common/portset.go
Labels: size/XL
