Repository np-guard/netpol-analyzer, pull requests merged in 2025-01, with the labels that each got.

#471 updating k8s.io related versions
  go.mod
  go.sum
Labels: size/M

#470 bump golang.org/x/net from v0.23.0 to v0.33.0
  go.mod
  go.sum
Labels: size/M

#477 update tests manifests
  test_outputs/connlist/anp_banp_blog_demo_connlist_output.csv
  test_outputs/connlist/anp_banp_blog_demo_connlist_output.dot
  test_outputs/connlist/anp_banp_blog_demo_connlist_output.json
  test_outputs/connlist/anp_banp_blog_demo_connlist_output.md
  test_outputs/connlist/anp_banp_blog_demo_connlist_output.txt
  tests/anp_banp_blog_demo/policies.yaml
  tests/anp_banp_blog_demo/workloads.yaml
Labels: size/L

#476 support ANPs on live-cluster
  cspell.json
  pkg/cli/evaluate.go
  pkg/cli/list.go
  pkg/cli/root.go
  pkg/internal/common/netpol_constants.go
  pkg/logger/logger.go
  pkg/netpol/connlist/connlist.go
  pkg/netpol/eval/resources.go
  pkg/netpol/internal/alerts/warnings.go
Labels: size/L

#490 remove external exposure from the exposure-analysis structs
  pkg/netpol/eval/check.go
  pkg/netpol/eval/internal/k8s/adminnetpol.go
  pkg/netpol/eval/internal/k8s/baseline_admin_netpol.go
  pkg/netpol/eval/internal/k8s/netpol.go
  pkg/netpol/eval/resources.go
Labels: size/L

#491 better policy and rules naming
  tests/exposure_test_with_anp_10_with_real_pod/policies.yaml
  tests/exposure_test_with_anp_11_with_named_port/policies.yaml
  tests/exposure_test_with_anp_12/policies.yaml
  tests/exposure_test_with_anp_13/policies.yaml
  tests/exposure_test_with_anp_15/policies.yaml
  tests/exposure_test_with_anp_4_entire_cluster_example/policies.yaml
  tests/exposure_test_with_anp_5_entire_cluster_example/policies.yaml
  tests/exposure_test_with_anp_6_entire_cluster_example/policies.yaml
  tests/exposure_test_with_anp_8/policies.yaml
  tests/exposure_test_with_anp_9/policies.yaml
Labels: size/M

#494 Issue 455 admin netpols test coverage
  pkg/netpol/connlist/connlist_test.go
  pkg/netpol/diff/diff_test.go
  pkg/netpol/eval/check.go
  pkg/netpol/eval/internal/k8s/adminnetpol.go
  pkg/netpol/eval/resources.go
  test_outputs/connlist/exposure_test_with_anp_16_exposure_output.csv
  test_outputs/connlist/exposure_test_with_anp_16_exposure_output.dot
  test_outputs/connlist/exposure_test_with_anp_16_exposure_output.dot.png
  test_outputs/connlist/exposure_test_with_anp_16_exposure_output.dot.svg
  test_outputs/connlist/exposure_test_with_anp_16_exposure_output.json
  test_outputs/connlist/exposure_test_with_anp_16_exposure_output.md
  test_outputs/connlist/exposure_test_with_anp_16_exposure_output.txt
  tests/anp_bad_path_test_19/anp.yaml
  tests/anp_bad_path_test_19/manifests.yaml
  tests/anp_bad_path_test_20/anps.yaml
  tests/anp_bad_path_test_20/manifests.yaml
  tests/banp_bad_path_test_15/banp_core_egress_sctp_rules.yaml
  tests/banp_bad_path_test_15/manifests.yaml
  tests/exposure_test_with_anp_16/deployments.yaml
  tests/exposure_test_with_anp_16/policies.yaml
Labels: size/XXL

#497 wrap error returned from metav1.LabelSelectorAsSelector to keep old versions error title string
  pkg/netpol/connlist/connlist_test.go
  pkg/netpol/eval/internal/k8s/adminnetpol.go
  tests/bad_netpols/subdir7/resources.yaml
Labels: size/L
